import Head from 'next/head'
import Layout from '@/Component/Layout'
import Image from 'next/image'
import profilePic from "../../public/images/profile/developer-pic-1.png"
import AnimatedText from '@/Component/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/Component/icons'
import Hireme from '@/Component/Hireme'
import useThemeSwitcher from '@/Component/useThemeSwitcher'
import { useEffect } from 'react';
import { useState } from 'react';



export default function Home() {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex items-center  text-dark w-full min-h-screen dark:text-light'>
       <Layout className='pt-0 md:pt-16 sm:pt-8'>
            <div className=' flex items-center justify-between lg:flex-col w-full '>

                <div className='w-1/2 p-8 lg:hidden md:inline-block lg:w-full lg:text-center md:w-full'>
                  <Image src={profilePic} alt='webahmad' className='w-full h-auto' priority sizes='(max-width: 786px) 100vw,(max-width:1200px) 50vw,50vw'/>
                </div>
              <div className='w-1/2 flex flex-col items-center self-senter lg:text-center '>
                <h1></h1>
                <AnimatedText text={"Turning Vision Into Reality With Code And Design."} className='!text-4xl !text-left xl:!text-3xl lg:!text-4xl lg:!text-center md:!text-3xl sm:!text-2xl'/>
                <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
                As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
                Explore my latest projects and articles, showcasing my expertise in React.js and web development. 
                </p>
                <div className="flex items-center self-start mt-2  lg:justify-center lg:w-full">
                  <Link href="/dummy.pdf" target="_blank"
                  className={`flex items-center bg-dark text-light p-2 px-3
                  rounded-lg text-md font-semibold hover:bg-light hover:text-dark 
                  border-2 border-solid border-transparent hover:border-dark
                    dark:bg-light dark:text-dark hover:dark:text-light hover:dark:bg-dark dark:border dark:border-solid dark:border-light`} download={"true"}
                  >Resume <LinkArrow className={"w-5 ml-1"}/></Link>
                  <Link href="mailto:www.at4675@gmail.com" target="_blank"
                  className='ml-2 text-dark font-medium capitalize text-lg underline dark:text-light'
                  >Contact</Link>
                </div>
              </div>

            </div>
       </Layout>
       <Hireme/>
       
       <div className='absolute right-0 bottom-2 inline-block w-20s'>
        
       </div>
      
      </main>
    </>
  )
}
